DryRedirect = true

ExpirationCheckInterval = "10s"
ExpirationDryRun = true

[BlockedHosts]
    Hosts = [
        "gme.sh",
        "github.com"
    ]


[Backends]
    PersistentBackend = "Mongo"
    StatsBackend = "Redis"
    PubSubBackend = "Redis"
    CacheBackend = "Shared"

[WebServer]
    # Address on which the WebServer should listen
    Addr = ":1336"

[Database]
    # Mongo, BBolt (embedded)
    Backend = "Mongo"
    EnableSharedCache = true

    # Persistent Database
    [Database.Mongo]
        ApplyURI = "mongodb://whgoxy_test:P9itnCl0SzMWeUKo@whgoxy-shard-00-00.x10rd.mongodb.net:27017,whgoxy-shard-00-01.x10rd.mongodb.net:27017,whgoxy-shard-00-02.x10rd.mongodb.net:27017/test?authSource=admin&replicaSet=atlas-lp4hj7-shard-0&readPreference=primary&appname=whgoxy&ssl=true"
        Database = "gme-sh"
        ShortURLCollection = "short-urls"
        MetaCollection = "meta"

    # Temporary Database
    [Database.Redis]
        Use = true
        Addr = "127.0.0.1:6379"
        Password = ""
        DB = 0

    # Persistent Database
    [Database.BBolt]
        Path = "dbgoesbrr.db"
        FileMode = 0666
        ShortedURLsBucketName = "stonks-urls"

    # Persistent Database
    # NOT IMPLEMENTED (yet)
    [Database.Maria]
        Addr = "127.0.0.1:3306"
        User = "user"
        Password = "123456"
        DBName = "stonksdb"
        TablePrefix = ""