version: "3.4"

services:

  #
  # MongoDB is used to store the shortend URLs
  # see https://hub.docker.com/_/mongo/
  # and https://www.mongodb.com
  #
  mongo:
    image: mongo:latest
    restart: unless-stopped

    volumes:
    - gmeshort-mongo-data:/data/db

  #
  # Redis is used for temporary stats
  # and for pub-sub use (caching)
  # see https://hub.docker.com/_/redis/
  # and https://redis.io
  #
  redis:
    image: redis:latest
    restart: unless-stopped

  #
  # Main app
  # see https://github.com/gme-sh/gme.sh-api
  #
  gmeshort:
    build: .
    restart: unless-stopped
    tty: true
    depends_on:
      - mongo
      - redis
    ports:
      - 1334:80
    env_file:
      - docker-compose.env

volumes:
  gmeshort-mongo-data: