version: "3.4"

services:

  #
  # Redis is used for temporary stats
  # and for pub-sub use (caching)
  # see https://hub.docker.com/_/redis/
  # and https://redis.io
  #
  redis:
    image: redis:latest
    restart: unless-stopped

  #
  # Main app
  # see https://github.com/gme-sh/gme.sh-api
  #
  gmeshort:
    build: .
    restart: unless-stopped
    tty: true
    depends_on:
      - redis
    ports:
      - 1334:80
    env_file:
      - docker-compose.env
    environment:
      GME_REDIS_ADDR: "redis:6379"