name: "Build Docker"

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    name: "Build Go"

    runs-on: ubuntu-latest

    steps:
      - name: "📝 Checkout Code"
        uses: actions/checkout@v2

      - name: "Create docker-compose.env"
        run: mv docker-compose.example.env docker-compose.env

      - name: "🏗 Docker-Compose Build"
        run: docker-compose build