name: "Build Docker"

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    name: "Build Docker"

    runs-on: ubuntu-latest

    steps:
      - name: "📝 Checkout Code"
        uses: actions/checkout@v2

      - name: "Create docker-compose.env"
        run: |
          mv docker/docker-compose.env ./docker-compose.env
          mv docker/docker-compose-redis-mongo.yml ./docker-compose.yml

      - name: "🏗 Docker-Compose Build"
        run: docker-compose build